### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by Flako007** [deyvissonbrenoveras/ovpnconfig.com.br#6]
Greetings Team,

We are having issues trying to access the URL: http://ovpnconfig.com.br/ and we dont know if there is a problem on the server or is something on our end. Please let me know if is working in order to make a verification on our end.

Thanks so much in advance for your help and support.

![image](https://user-images.githubusercontent.com/131787202/234311452-6bdd33c9-205e-4d2f-a29e-d60bec7e51ca.png)

**Comment by deyvissonbrenoveras** [comment]
Thank you for reporting, the problem was resolved.

**Comment by Flako007** [comment]
Thanks so much for all your help and support.
